### ISSUE TITLE
/list makes weird error show up? 

### ISSUE THREAD

**Issue by s4dpotato** [francojreyes/reminder-bot#1]
it worked before but now this keeps showing up 
![Screenshot_20220901_150547](https://user-images.githubusercontent.com/112544586/187921221-a38dc643-97aa-468b-ac76-355e2a5addcc.jpg)

also the last reminder was on the list and then it didn't actually do the reminder but it was gone from the list, idk what could've caused that

**Comment by francojreyes** [comment]
Discord's new Message Intents broke the bot. Should be fixed now. Sorry about that.
