### ISSUE TITLE
bot doesn't send some reminders 

### ISSUE THREAD

**Issue by s4dpotato** [francojreyes/reminder-bot#2]
i use the bot to do reminders for the matches of a tournament. 
however sometimes it doesn't do the reminder but when i check i had set one and i also didn't get the time wrong or anything. it only happens for some reminders, not all of them and they're always gone from the list after

**Comment by francojreyes** [comment]
Thank you for letting me know, looking into this issue now.

**Comment by francojreyes** [comment]
I've pushed a fix now. Let me know if the issue persists.
